---
- name: Add dockerproject.org repository key
  apt_key: keyserver='hkp://p80.pool.sks-keyservers.net:80' id=58118E89F3A912897C070ADBF76221572C52609D state=present

- name: Add dockerproject.org repository
  apt_repository: repo='deb http://apt.dockerproject.org/repo {{ ansible_distribution | lower }}-{{ ansible_distribution_release }} main'
